### ISSUE TITLE
wish: clarify in the docs if the screenshots are stored in memory or disk

### ISSUE THREAD

**Issue by markstos** [mihalea/i3expo#3]
If the screenshots are stored on disk, there is a privacy concern that you might unintentionally preserve a screenshot of a password, Incognito window or other sensitive content.

**Comment by mihalea** [comment]
I have addressed your concerns and the readme now contains information on the security of the program. As a summary, screenshots aren't stored on disk, but only in memory, and it shouldn't pose a security risk.

**Comment by markstos** [comment]
Thanks!
